name: Docker build and push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs can run sequentially or in parallel
jobs:
  build-app:
    # On which runner will the job run
    runs-on: ubuntu-latest

    steps:
      # Checkout our repository
      -
        name: checkout repository
        uses: actions/checkout@v2

      # Set up execution environment for the containers
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      # more extensive interface to build our docker image
      -
        name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      
      # Login to DockerHub
      # Docker secrets are created in Github current repository: tab Settings/Secrets
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build and push docker image
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: xpadro/python-github-actions:latest
      